### ISSUE TITLE
Add secp384mlkem1024 combination

### ISSUE THREAD

**Issue by kriskwiatkowski** [post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-kyber#12]

**Comment by csosto-pk** [comment]
@kriskwiatkowski , I don't think we need to add secp384mlkem768 to [draft-kwiatkowski-tls-ecdhe-kyber](https://github.com/post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-kyber). This draft was to only get a temporary identifier to negotiate in TLS 1.3 until we have the final ML-KEM. I don't think we need another temporary one for ML-KEM-768. We can wait to get secp384mlkem768 from https://datatracker.ietf.org/doc/draft-ietf-tls-hybrid-design/

**Comment by kriskwiatkowski** [comment]
ok
