### ISSUE TITLE
Sizes of key shares are off-by-one

### ISSUE THREAD

**Issue by kriskwiatkowski** [post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-kyber#7]
I get off-by-one for the sizes of key shares.

The given size of client key share seems to be size of kyber public key
plus 64 bytes, and given size of server key share seems to be the size
of kyber ciphertext plus 64 bytes.

However, the difference is stated to be UncompressedPointRepresentation
for P256 from TLS 1.3. AFACIT, that is 65 bytes (1 legacy_form byte,
32 bytes for x, 32 bytes for y).

So I get that the client share should be 1249 bytes (instead of 1248
bytes) and the server key share should be 1153 bytes (instead of 1152
bytes).

Obviously something is wrong somewhere, but where?

**Comment by csosto-pk** [comment]
Hi Kris,
Indeed, I did a capture in TLS 1.3 and the `secp256r1` `keyshare` is 65bytes. So the stated lengths should be 1249 and 1153.

**Comment by kriskwiatkowski** [comment]
@csosto-pk Thanks for checking that. Indeed, it seems I've missed ``legacy_form`` bytes. I'll fix that.
